version: "3.8"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=testpass123
      - DB_NAME=codeChallengeHub
      - DB_PORT=3306
      - SESSION_SECRET=your-secret-key
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: testpass123
      MYSQL_DATABASE: codeChallengeHub
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ptestpass123"] # Use the correct password
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  mysql_data:
    name: codechallengehub_mysql_data
  submissions:
  problems:

networks:
  app-network:
    driver: bridge
