FROM golang:1.21-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o judge ./judge/main.go

RUN mkdir -p /app/temp

RUN chown -R nobody:nobody /app
USER nobody

EXPOSE 8081

CMD ["./judge"]